name = "DataManifest"
uuid = "b8ee69ef-a20a-4d38-bceb-a68d72817f72"
authors = ["Mah√© Perrette <mahe.perrette@gmail.com>"]
version = "0.8.1"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
URIs = "1"
julia = "1.6"
